### ISSUE TITLE
Suppressing output during model fitting

### ISSUE THREAD

**Issue by studerus** [kapelner/bartMachine#4] opened 2014-09-07 10:38 UTC
Is it possible to suppress output messages completely when running bartMachine? I tried verbose = F and even redirecting the output to a temporary file to no avail.

```
set.seed(11)
n  = 200 
p = 5
X = data.frame(matrix(runif(n * p), ncol = p))
y = 10 * sin(pi* X[ ,1] * X[,2]) +20 * (X[,3] -.5)^2 + 10 * X[ ,4] + 5 * X[,5] + rnorm(n)

sink(file = tempfile())
bartMachine(X, y, verbose = F)
sink()
```

**Comment by berndbischl** [comment] 2015-01-23 14:44
Any news on this?

**Comment by kapelner** [comment] 2015-01-23 20:29
I think that's fixed in the new release. If not, please paste the aberrant
behavior in this thread.

**Comment by jakob-r** [comment] 2015-02-03 17:36
With the newest version from github we can turn off `verbose = FALSE` successfully but still capture.output fails
```r
set.seed(11)
n  = 200 
p = 5
X = data.frame(matrix(runif(n * p), ncol = p))
y = 10 * sin(pi* X[ ,1] * X[,2]) +20 * (X[,3] -.5)^2 + 10 * X[ ,4] + 5 * X[,5] + rnorm(n)

p.m = capture.output(m <- bartMachine(X, y, verbose = T))
pr.m
```

**Comment by kapelner** [comment] 2015-02-03 23:26
Hi Jakob,

Sorry... I'm having trouble understanding this. I get:

> library(bartMachine)
> set.seed(11)
> n  = 200
> p = 5
> X = data.frame(matrix(runif(n * p), ncol = p))
> y = 10 * sin(pi* X[ ,1] * X[,2]) +20 * (X[,3] -.5)^2 + 10 * X[ ,4] + 5 *
X[,5] + rnorm(n)
>
> p.m = capture.output(m <- bartMachine(X, y, verbose = FALSE))
> p.m
character(0)

So verbosity FALSE seems to work.

Now you're asking what if verbose is TRUE? I get:

> p.m = capture.output(m <- bartMachine(X, y, verbose = T))
> p.m
[1] "bartMachine initializing with 50 trees..."   "Now building bartMachine
for regression ..."
[3] "evaluating in sample data...done"

And you are saying this fails. Why? Because you're not seeing the Java
standard out? I've noticed on some windows machine rJava fails to even
display the standard out.

But on Linux I get:

> p.m = capture.output(m <- bartMachine(X, y, verbose = T))
building BART with mem-cache speedup...
Iteration 100/1250
Iteration 200/1250
Iteration 300/1250
Iteration 400/1250
Iteration 500/1250
Iteration 600/1250
Iteration 700/1250
Iteration 800/1250
Iteration 900/1250
Iteration 1000/1250
Iteration 1100/1250
Iteration 1200/1250
done building BART in 5.489 sec

burning and aggregating chains from all threads... done
> p.m
[1] "bartMachine initializing with 50 trees..."
[2] "Now building bartMachine for regression ..."
[3] "evaluating in sample data...done"

Thus capture.output does not capture the Java standard out.

Adam

On Tue, Feb 3, 2015 at 12:36 PM, Jakob Richter <notifications@github.com>
wrote:

> With the newest version from github we can turn off verbose = FALSE
> successfully but still capture.output fails
>
> set.seed(11)n  = 200 p = 5X = data.frame(matrix(runif(n * p), ncol = p))y = 10 * sin(pi* X[ ,1] * X[,2]) +20 * (X[,3] -.5)^2 + 10 * X[ ,4] + 5 * X[,5] + rnorm(n)
> p.m = capture.output(m <- bartMachine(X, y, verbose = T))pr.m
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kapelner/bartMachine/issues/4#issuecomment-72696385>.
>



-- 
Adam Kapelner, Ph.D.
Assistant Professor of Mathematics
Queens College, City University of New York
64-19 Kissena Blvd Room 325
Flushing, NY, 11367
kapelner.com

**Comment by jakob-r** [comment] 2015-02-04 00:20
It works exactly like you said. So I think I just confused the java standard output (`building BART with mem-cache speedup...`) with the learner output. The learner output will be successfully captured and thus hidden.
So it's a matter of the java standard output. So i think this issue can be closed.

**Closed** 2015-02-04 00:34 UTC
