### ISSUE TITLE
"seed = " doesn't seem to work with k_fold_cv

### ISSUE THREAD

**Issue by schwa021** [kapelner/bartMachine#32] opened 2020-08-25 19:38 UTC
Hello, 

Thanks for the amazingly great package! I'm loving it, and able to do lots of useful things.

I seem to have found a minor bug related to creating reproducible results. 

When I run _k_fold_cv_ several times with the same seed, I get different results. I assumed the _seed =_ would work the same way it works in build_bart_machine. 

Example below (ignore the poor classification results - those are unrelated to the issue)

oos_stats <- k_fold_cv(xx, ww, k_folds = 5, seed = 82002)
.predicting probabilities where "1" is considered the target level...
.predicting probabilities where "1" is considered the target level...
.predicting probabilities where "1" is considered the target level...
.predicting probabilities where "1" is considered the target level...
.predicting probabilities where "1" is considered the target level...

> oos_stats$confusion_matrix
           predicted 1 predicted 0 model errors
actual 1         6.000     129.000        0.956
actual 0         8.000    1915.000        0.004
use errors       0.571       0.063        0.067

Then run again....

> oos_stats <- k_fold_cv(xx, ww, k_folds = 5, seed = 82002)
.predicting probabilities where "1" is considered the target level...
.predicting probabilities where "1" is considered the target level...
.predicting probabilities where "1" is considered the target level...
.predicting probabilities where "1" is considered the target level...
.predicting probabilities where "1" is considered the target level...

> oos_stats$confusion_matrix
           predicted 1 predicted 0 model errors
actual 1           4.0     131.000        0.970
actual 0           6.0    1917.000        0.003
use errors         0.6       0.064        0.067

**Comment by kapelner** [comment] 2020-08-25 19:45
Did you set the seed in R before running the k fold CV? The only randomness
I see is line 32 of the Bart package cross validation file which is calling
rnorm. Its output should be deterministic if you set a seed right before
running the k fold CV function.

**Comment by schwa021** [comment] 2020-08-25 22:03
First of all... wow! Thanks for the extremely quick reply.

Second, I had *not* set the seed in R, since this did not work for build_bart_machine (however, setting seed = xx did work).

I re-tried setting the seed in R immediately before calling, and it still did not work. Please see below:


> # Get CV performance
**> set.seed(82002)**
> oos_stats <- k_fold_cv(xx, ww, k_folds = 5, prob_rule_class = .2)
.predicting probabilities where "1" is considered the target level...
.predicting probabilities where "1" is considered the target level...
.predicting probabilities where "1" is considered the target level...
.predicting probabilities where "1" is considered the target level...
.predicting probabilities where "1" is considered the target level...

> oos_stats$confusion_matrix
           predicted 1 predicted 0 model errors
actual 1        55.000      92.000        0.626
actual 0       148.000    1813.000        0.075
use errors       0.729       0.048        0.114


> # Get CV performance
**> set.seed(82002)**
> oos_stats <- k_fold_cv(xx, ww, k_folds = 5, prob_rule_class = .2)
.predicting probabilities where "1" is considered the target level...
.predicting probabilities where "1" is considered the target level...
.predicting probabilities where "1" is considered the target level...
.predicting probabilities where "1" is considered the target level...
.predicting probabilities where "1" is considered the target level...

> oos_stats$confusion_matrix
           predicted 1 predicted 0 model errors
actual 1        52.000       95.00        0.646
actual 0       144.000     1817.00        0.073
use errors       0.735        0.05        0.113

I also tried setting the seed outside *and* inside - but this also did not work.

**Comment by kapelner** [comment] 2020-08-25 22:08
Why are you not setting the seed also in the k fold CV function?

**Comment by schwa021** [comment] 2020-08-25 22:15
I tried that and it didn't work (see end of last comment - which I should have put earlier in my reply). 

Here are the results:


> # Get CV performance
> set.seed(82002)
> oos_stats <- k_fold_cv(xx, ww, k_folds = 5, prob_rule_class = .2, seed = 82002)
.predicting probabilities where "1" is considered the target level...
.predicting probabilities where "1" is considered the target level...
.predicting probabilities where "1" is considered the target level...
.predicting probabilities where "1" is considered the target level...
.predicting probabilities where "1" is considered the target level...

> oos_stats$confusion_matrix
           predicted 1 predicted 0 model errors
actual 1        90.000     106.000        0.541
actual 0       208.000    1599.000        0.115
use errors       0.698       0.062        0.157
> # Get CV performance
> set.seed(82002)
> oos_stats <- k_fold_cv(xx, ww, k_folds = 5, prob_rule_class = .2, seed = 82002)
.predicting probabilities where "1" is considered the target level...
.predicting probabilities where "1" is considered the target level...
.predicting probabilities where "1" is considered the target level...
.predicting probabilities where "1" is considered the target level...
.predicting probabilities where "1" is considered the target level...

> oos_stats$confusion_matrix
           predicted 1 predicted 0 model errors
actual 1        92.000     104.000        0.531
actual 0       207.000    1600.000        0.115
use errors       0.692       0.061        0.155

**Comment by kapelner** [comment] 2020-08-25 22:35
Can you check if oos_stats$folds_vec is the same?

**Comment by schwa021** [comment] 2020-08-25 22:43
They are the same. I set the seed outside and inside and ran twice. Each time I extracted folds (folds1 and folds2). Below is the difference (truncated - but the rest are zero also)

folds1 - folds2
   [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  [41] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  [81] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [121] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [161] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [201] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [241] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [281] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [321] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [361] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [401] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [441] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [481] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [521] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [561] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [601] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [641] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [681] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [721] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [761] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [801] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [841] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [881] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [921] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [961] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [ reached getOption("max.print") -- omitted 740 entries ]

**Comment by kapelner** [comment] 2020-08-26 03:10
You're going to have to send your data because I'm experiencing the expected behavior:

```
> options(java.parameters = "-Xmx10g")
> pacman::p_load(bartMachine)
> 
> X = MASS::Boston[, 1:13]
> y = MASS::Boston[, 14]
> 
> set.seed(1984)
> k_fold_res = k_fold_cv(X, y, seed = 1984)
.....
> k_fold_res$rmse
[1] 3.293403
> set.seed(1984)
> k_fold_res = k_fold_cv(X, y, seed = 1984)
.....
> k_fold_res$rmse
[1] 3.293403
> 
> 
> y_binary = factor(ifelse(y > mean(y), "expensive", "inexpensive"))
> set.seed(1984)
> k_fold_res = k_fold_cv(X, y_binary, prob_rule_class = .2, seed = 1984)
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...

> k_fold_res$confusion_matrix
                   predicted expensive predicted inexpensive model errors
actual expensive               194.000                15.000        0.072
actual inexpensive              86.000               211.000        0.290
use errors                       0.307                 0.066        0.200
> set.seed(1984)
> k_fold_res = k_fold_cv(X, y_binary, prob_rule_class = .2, seed = 1984)
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...

> k_fold_res$confusion_matrix
                   predicted expensive predicted inexpensive model errors
actual expensive               194.000                15.000        0.072
actual inexpensive              86.000               211.000        0.290
use errors                       0.307                 0.066        0.200
```

**Comment by schwa021** [comment] 2020-08-26 12:13
Hi Adam,

Once again, I truly appreciate the time and effort you are putting into this. I am constantly amazed at the helpfulness of the online R community!

Something very interesting is going on, in my opinion. Rather than sending you my data, I ran **your** code on my machine. Amazingly, the results were **NOT** reproducible on my setup. By the way, I ran it a third time and got a third different answer.

The results (copied from my console) are below. I have also attached a "diagnostics report" from Rstudio created immediately after seeing this resutl (i.e. no changes to my setup/system). I am neither a developer nor an R expert - just an ordinary scientist user - so perhaps there are other things I can do to figure this out. 

X = MASS::Boston[, 1:13]
y = MASS::Boston[, 14]
y_binary = factor(ifelse(y > mean(y), "expensive", "inexpensive"))

set.seed(1984)

k_fold_res = k_fold_cv(X, y_binary, prob_rule_class = .2, seed = 1984)
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...

 k_fold_res$confusion_matrix
                   predicted expensive predicted inexpensive model errors
actual expensive               196.000                13.000        0.062
actual inexpensive              87.000               210.000        0.293
use errors                       0.307                 0.058        0.198

set.seed(1984)

k_fold_res = k_fold_cv(X, y_binary, prob_rule_class = .2, seed = 1984)
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...

 k_fold_res$confusion_matrix
                   predicted expensive predicted inexpensive model errors
actual expensive               197.000                12.000        0.057
actual inexpensive              86.000               211.000        0.290
use errors                       0.304                 0.054        0.194

set.seed(1984)

k_fold_res = k_fold_cv(X, y_binary, prob_rule_class = .2, seed = 1984)
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...

 k_fold_res$confusion_matrix
                   predicted expensive predicted inexpensive model errors
actual expensive               195.000                14.000        0.067
actual inexpensive              85.000               212.000        0.286
use errors                       0.304                 0.062        0.196

[diagnostics-report.txt](https://github.com/kapelner/bartMachine/files/5129689/diagnostics-report.txt)

**Comment by schwa021** [comment] 2020-08-26 12:29
another update - I re-started Rstudio, and ONLY loaded the bartMachine package - and was then able to re-create your results. So it appears to be a case of some sort of interference between packages.

I assumed that by loading bartMachine last (which is what I had been doing) this would not be the case.

So I guess my task is to figure out which package is causing the problems.

**Comment by kapelner** [comment] 2020-08-26 12:59
I'm so glad my package is not responsible for this bug.

When you figure it out, please post here and close the issue.

**Comment by schwa021** [comment] 2020-08-26 13:41
Hi Adam - sorry to keep bothering you, but hopefully this information will help improve an already-great package.

I believe the package conflict was a red herring. I think the problem actually lies with using multiple cores. Below is some code where you can reproduce the problem. I used your Boston Housing example. You will see that the first two times through (single-core) it works (produces same result). However, I then switch to a 4-core option using set_bart_machine_num_cores(4) and run again. At this point you will see that it no longer reproduces the same result.

As noted above, I'm not a software expert - but it seems plausible that different cores are being used for different chains on subsequent runs, or something like that. And, if each core has its own random number sequence, this could be the issue.

The code/output is below - taken line-for-line from my console. This starts with a fresh-restart of Rstudio and no other packages loaded.


> options(java.parameters = "-Xmx8g")
> library(bartMachine)

Loading required package: rJava
Loading required package: bartMachineJARs
Loading required package: randomForest
randomForest 4.6-14
Type rfNews() to see new features/changes/bug fixes.
Loading required package: missForest
Loading required package: foreach
Loading required package: itertools
Loading required package: iterators
Welcome to bartMachine v1.2.5.1! You have 7.64GB memory available.

If you run out of memory, restart R, and use e.g.
'options(java.parameters = "-Xmx5g")' for 5GB of RAM before you call
'library(bartMachine)'.

> 
> X = MASS::Boston[, 1:13]
> y = MASS::Boston[, 14]
> 
> y_binary = factor(ifelse(y > mean(y), "expensive", "inexpensive"))
> 
> set.seed(1984)
> k_fold_res = k_fold_cv(X, y_binary, prob_rule_class = .2, seed = 1984)
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...

> k_fold_res$confusion_matrix
                   predicted expensive predicted inexpensive model errors
actual expensive               194.000                15.000        0.072
actual inexpensive              86.000               211.000        0.290
use errors                       0.307                 0.066        0.200
> 
> set.seed(1984)
> k_fold_res = k_fold_cv(X, y_binary, prob_rule_class = .2, seed = 1984)
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...

> k_fold_res$confusion_matrix
                   predicted expensive predicted inexpensive model errors
actual expensive               194.000                15.000        0.072
actual inexpensive              86.000               211.000        0.290
use errors                       0.307                 0.066        0.200
> set_bart_machine_num_cores(4)
bartMachine now using 4 cores.
> 
> set.seed(1984)
> k_fold_res = k_fold_cv(X, y_binary, prob_rule_class = .2, seed = 1984)
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...
.predicting probabilities where "expensive" is considered the target level...

> k_fold_res$confusion_matrix
                   predicted expensive predicted inexpensive model errors
actual expensive               195.000                14.000        0.067
actual inexpensive              87.000               210.000        0.293
use errors                       0.309                 0.062        0.200
>

**Comment by kapelner** [comment] 2020-08-26 13:56
Of course. You cannot set the seed and expect deterministic output for more than one core. The reason is the cores are computing different Gibbs chains and you can't control which core fires when. (Maybe you can, but I don't have time to figure it out now...)

This is partially our fault. I thought I put this in the paper but I can't seem to find it now. Sorry about this whole mess.
I really should make a warning to the user if they set the seed and `num_cores > 1`. I'll do this for the next release.

**Closed by kapelner** 2020-08-26 13:56 UTC
